---
- hosts: ub-nas-01
  tasks:
  - copy:
      src: webfile.rb
      dest:  /home/muster/prod/temp/folder/web1conf.rb
      owner: muster
      group: muster

  - name: restart ruby
    command: touch /home/muster/prod/temp/restart.txt
    
